name: tornado-labels
channels:
  - conda-forge
dependencies:
  - python=3.10
  - rasterio
  - pillow
  - numpy
  - matplotlib
  - pip
  - pip:
      - tqdm
      - roboflow
      - python-dotenv
      - streamlit
