name: tornado-labels
channels:
  - conda-forge
dependencies:
  - python=3.10
  - gdal
  - rasterio
  - fiona
  - pyproj
  - shapely
  - geopandas
  - pillow
  - pip
  - pip:
      - tqdm
      - opencv-python
      - matplotlib
      - pycocotools
      - segment-geospatial
      - x-anylabeling
